### PR TITLE
Faster filter pool

### PR DESCRIPTION
**Pull request by necrolyte2**
This has master merged into it which is why it has so many commits. It really feels like I should rebase in this situation, but that article I read makes me scared to do it.

I have no way of doing an actual test to watch and see that this is doing what we intend, but it seems like it should and doesn't require extra code to do so. I may be missing what the group function was doing though

### CODE REVIEW

**Comment by necrolyte2** [comment]
I removed the master merge so the PR is cleaner

**Comment by averagehat** [comment]
LGTM. That group function was just a manual way of controlling how many processes get created, which `multiprocessing.Pool(N)` does better. 

Did you mean to pull against `faster-fasta`? That's a branch I made accidentally.

**Comment by necrolyte2** [comment]
I meant it to go to faster filter

**Comment by averagehat** [comment]
Closed in favor of #228

**Pull request closed without merging**
