### PR TITLE
Conda install

### PR DESCRIPTION
**Pull request by necrolyte2**
Todo:
* [x] .travis.yml
* [x] tox.ini
* [x] remove old vagrant tests
* [x] fix install docs
* [x] ~~Ensure #76 still working~~ Replaced with Read the docs
* [x] put requirements for bwa/samtools/trimmomatic... into requirements file
* [x] install.sh to replace majority of scripts: part of .travis.yaml
* [x] primer trimming docs
* [ ] primer can be in samplesheet
* [ ] update samplesheet docs to include primer file info

Related #17 #52

### CODE REVIEW

**Comment by necrolyte2** [comment]
Assuming passed checks this is good to go

`install.sh` will likely need some love at some point, but I think it better to allow users to give us indications of how they use it prior to trying to add a bunch of options that may not get used

**Comment by averagehat** [comment]
just added docs in last two builds. forgot [skip ci]

**Comment by necrolyte2** [comment]
I just realized that we need support for the primer file to be included in the samplesheet as well. Adding to checklist

**Comment by averagehat** [comment]
merging this for the miniconda portion. the rest of the primer file stuff is in #191

**Pull request merged**
